#!/bin/bash
date=`date +%m.%d.%y-%H%M`;
sspath="/mnt/dylix/public_html/screenshots";
#composite -gravity southeast /mnt/dylix/public_html/screenshots/deadarea2.png /mnt/dylix/public_html/screenshots/ss-$date.jpg /mnt/dylix/public_html/screenshots/ss-$date.jpg

composite -gravity west $sspath/ss-$date.png $sspath/blank.png $sspath/ss-$date.png

// 6900 x 1080

echo "http://dylix.dyndns.org/screenshots/ss-$date.jpg" # | xclip
#echo `/home/dylix/scripts/ompload -n -u /mnt/dylix/public_html/screenshots/ss-$date.jpg`
echo "Screenshot successfully taken.."
sleep 1000
#exit

## Old thumbnail generator
##
#convert $sspath/ss-$date.png $sspath/ss-$date.jpg
#echo -n "Would you like to create a 100x75 size thumbnail? (yes or no): "
#read -e THUMB
#if [ "$THUMB" = "yes" ]; then
#   convert $sspath/ss-$date.png -resize 100x75 $sspath/ss-$date-thumb.png
#   echo "thumbnail created.."
#fi
#
#echo -n "Would you like to create a 341x256 size thumbnail? (yes or no): "
#read -e BIGTHUMB
#if [ "$BIGTHUMB" = "yes" ]; then
#   convert $sspath/ss-$date.png -resize 341x256 $sspath/ss-$date-med.png
#   echo "bigger thumbnail created.."
#fi
