#!/bin/sh
/usr/bin/numlockx &
sleep .1; /usr/bin/devilspie &
/usr/bin/pidgin &
/usr/bin/lomoco -g &
/home/dylix/.dropbox-dist/dropboxd &
/usr/bin/conky &
#/usr/bin/conky -c ~/.conkyrc-fortune &
#/usr/bin/guake &
#xfwm4 --replace
/home/dylix/scripts/irssi.sh &
pkill synergys
/usr/bin/synergys -f --debug ERROR --name reaction -c /home/dylix/.synergy.conf --address :24800 &
#/usr/bin/skype &
LD_PRELOAD=/usr/lib32/libv4l/v4l1compat.so skype &
#/usr/bin/compiz-manager --replace --loose-bindings &
